### PR TITLE
README Updated

### PR DESCRIPTION
**Pull request by czgdp1807**

### CODE REVIEW

**Comment by czgdp1807** [comment]
@cipheraxat Please merge this.

**Comment by cipheraxat** [comment]
Hey, @czgdp1807 Could add more description about the project in the readme file so that people aware of the libraries and algorithms used.
You can follow this for more information - https://www.udacity.com/course/writing-readmes--ud777

**Comment by czgdp1807** [comment]
We are implementing all algorithms from scratch. We are only using python for development purposes. Helping points for testing are also given. IMHO, the README is having all the necessary information for anyone who is interested in contributing to the project.

**Comment by cipheraxat** [comment]
Okay @czgdp1807 just keep updating the readme, so that student/mentors visiting it has the idea on what your are working

**Pull request merged**
